# Generated by Django 2.2.5 on 2019-12-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
